#!/bin/bash

# TODO: Should we source the env vars?
echo $0
if [ "$1" == "" ]; then
    echo "Usage: build <env_vars_file>"
    exit
fi


pwd=`pwd`
env_file="${pwd}"/"$1"
echo "Sourcing $env_file"
source $env_file

# Build Scratchcard Docker image
docker build -t scratchcard:latest --build-arg CERT_PASSPHRASE=${CERT_PASSPHRASE} .

# Run docker-compose
docker-compose -f ./test/docker-compose.yml up -d

# Build and run protractor
docker build -t protractor ./test/protractor
docker run protractor
